### ISSUE TITLE
Odd issue with FeCs after CAN Gateway swap

### ISSUE THREAD

**Issue by bignick8t3** [harman-f/MHI2_MIB2_AIO_FW_Update_Template#10]
I have a Skoda Octavia and obtained the 9" screen and a MIB2 unit from a Superb.

Using the G11 firmware and then the G11 to G13 all went well and everything was as expected.

The Canton sound system, Virtual Cockpit everything worked apart from me getting the menu within the MIB for the VC.
This was down to having a 5Q gateway, I had a 3Q installed and the FeCs restored, an added bonus was the removal of the CP warning from the MIB and the gateway.

However the MIB now rejects the FeCs meaning I've nothing but the radio, so no Nav, AA, Bluetooth etc.
The error against the FeCs is "Temporarily Rejected".

I tried running the patch again but this detects the patch already in place so does nothing, I've also tried running the G13 firmware update (AIO) again but again as it detects everything is up to date it doesn't make a difference.

Just after some ideas of what I can do if anything?
Is there a way to force an update even to the same version so it overwrites everything again at all?

Thanks,

Nick

**Comment by harman-f** [comment]
You log files would help.

So someone did a Componet Protection removal after chnaging Gateway for GW and MIB unit?

This does normally not effect the patch...

**Comment by bignick8t3** [comment]
That's correct.

It struck the chap that did it odd as well.

Log files from the attempt of reflashing the firmware or an attempt to reapply the patch?

Thanks

**Comment by bignick8t3** [comment]
So I found the option whereby the update runs regardless of what is currently installed.
I ran an update which completed successfully but I still get the fecs with "Temporarily Rejected".

Attached is the log file and a picture of an fec from the installed list.

Thanks
[MU1440-JTB-07425.04.16118105F3.log](https://github.com/harman-f/MHI2_MIB2_AIO_FW_Update_Template/files/11382339
![IMG20230503130819 (Medium)](https://user-images.githubusercontent.com/11718874/235913695-061971a3-e87c-4ca0-8431-a179c7d85281.jpg)
/MU1440-JTB-07425.04.16118105F3.log)

**Comment by harman-f** [comment]
Log Output looks strange. 

You only used the AIO or also normal M.I.B?

**Comment by bignick8t3** [comment]
For the last log that was from the AIO update.

One before that might have been MIB

**Comment by harman-f** [comment]
Can you show your whole FEC list. Do you have double entries?


Install M.I.B again. Installation will remove non valid Fecs from unit.

**Comment by bignick8t3** [comment]
Ah yes there are duplicate FECs.

So just install the M.I.B toolbox again via SD card?

**Comment by bignick8t3** [comment]
So I installed the M.I.B again and the FECs just seem to keep getting added.

For example 00030000 is in the list 6 times, I'm a little stumped to be honest.

Any help is greatly appreciated.

**Comment by harman-f** [comment]
Did you do a function restore via ODIS?

M.I.B is unsing your the last factory FEC on Unit to apply new FECs.
It looks like this one is not matching your hardware anymore after the new CP was applied.

**Comment by bignick8t3** [comment]
I believe that the chap that did the gateway swap may have done that yes.

The car came with an Amundsen MIB2 Standard.

Is there anything I can do as trying to reapply the patch doesn't seem to work as it detects that the patch is already in place?

**Comment by harman-f** [comment]
get a fresh backup with M.I.B and share that.

Have to look at the Fec files

**Comment by bignick8t3** [comment]
Will do.

Many thanks again.

**Comment by harman-f** [comment]
There is a new "factory" FecContainer on unit - created on 24/04/2023
So this looks fine:
![image](https://user-images.githubusercontent.com/98130152/236260714-474a16df-764c-4acb-8de3-22edfeb181b6.png)

Normally, this FecContainer is used to add new once.

I currently would assume, that your unit is not patched anymore...
But it must be, as you used the AIO...

I would suggest, that you patch again with M.I.B
To be able you have to rename the patch file.
Rename: MU1440-ifs-root-part2-0x00ba0000-1C06F300.ifs
To: File MU1440-ifs-root-part2-0x00ba0000-2006F300.ifs

And run the patch command in M.I.B again.

**Comment by bignick8t3** [comment]
Wow excellent work, all is working again now!

Many thanks for your time and effort I really do appreciate it.

Nick
