### ISSUE TITLE
Error 134

### ISSUE THREAD

**Issue by ErikDublin** [harman-f/MHI2_MIB2_AIO_FW_Update_Template#19]
Getting error 134, there is a list with this errors to troubleshoot?
Thanks!

**Comment by ErikDublin** [comment]
Actually, sorted, sorry Gracenote2 was missing. Ty

**Comment by ASENK12** [comment]
Hola buenas 🖐️ 
Yo tengo el mismonproblema cuando queroninstalar Firmware VW G11_K3342 me sale el mismo error.
Como puedo arreglar?
Gracias
