### ISSUE TITLE
[ HELP ] - VW Golf 7 (2015)

### ISSUE THREAD

**Issue by socialvodsud** [harman-f/MHI2_MIB2_AIO_FW_Update_Template#2]
Hello,
Yesterday my Golf 7 (late 2015) popped up saying that car play, bluetooth etc was not working and that I needed to enter an activation code.

Current software version MHI2_ER_VWG11_S2103

Will this project work for me to achieve unlocking of all services?

Alternatively, what tool should I use?

Thank you all very much. I will then support the project financially if necessary.

Thank you
Robert

**Comment by harman-f** [comment]
Yes, you can.

get in contact on telegram https://t.me/MIB_Contact

**Comment by harman-f** [comment]
Yes, you can run the VWG11 AIO to undate and patch your unit.
However, full download of the FW is not possible here.

**Comment by harman-f** [comment]
https://mibsolution.one/#/1/9/MHI2%20-%20HARMAN/Firmware
