### ISSUE TITLE
Unbrick mhi2

### ISSUE THREAD

**Issue by ganniballector** [harman-f/MHI2_MIB2_AIO_FW_Update_Template#4]
Hi guys.  Help who can.  Car Volkswagen Golf 7 variant 2018. MHI2 Got a black screen.  Resetting the terminal does not help.  History: originally firmware MHI2_JP_VW48x_P1001, there is an SD with MIB, a full backup was made, made a second SD with MHI2_ER_VWG11_K3342_1_AIO_MU1427_20230318, copied to the second SD Gracenote2_AIO_payload, made by Swdlautorun.  I inserted SD with MIB into the first slot SD1, inserted the second SD with FW into the second slot SD2.  Auto-installation started, 8 blocks were determined for installation, installation went on, an error occurred on one of the blocks (about loading European covers), I pressed SKIP, the error window closed, the firmware continued, upon completion, reboot (disconnected) and a black screen.  something makes a sound twice, peak piiiik, the radio tape recorder does not respond to pressing.

**Comment by ganniballector** [comment]
I left the MIB in the slot, since the instructions for the MIB indicate that the MIB should always be in the SD1 slot.  I did the conversion using MIB, and checked that everywhere the region became EU instead of JP.  The battery was completely disconnected and (+) and (-), for about 5 minutes.  Nothing has changed, when the ignition is turned on, the same black screen.  Unfortunately there is no photo of the error, but the speech in the error was about RadioStationDB or something related to the radio.

**Comment by harman-f** [comment]
Check FW SD Card for log file.

**Comment by ganniballector** [comment]
there is nothing in the backup\logs folder.  if you are talking about it

**Comment by ganniballector** [comment]
> Так что финальный скрипт не запустился.
> 
> Можно попробовать с d-Link, если можно подключиться к mmx или rcc.
> 
> Скорее всего нужен UART.

есть инструкция как это сделать и что должен получить? завтра поеду брать dlink dub e100 usb 2.0 надеюсь он его увидит

**Comment by harman-f** [comment]
let's start with D-Link.

Some instructions on hwo to connect can be found on mibwiki.one

**Comment by harman-f** [comment]
any news here?

**Comment by ganniballector** [comment]
Пока новостей нет. Вчера пришли UART, начал разбирать машину чтоб снять mib, не смог разобраться как его вытащить из бардачка. В общем на днях подключусь к нему, и продолжим разбираться что прошло не так

**Comment by harman-f** [comment]
any update here?
