### ISSUE TITLE
NAR G11 to G13 FW Conversion

### ISSUE THREAD

**Issue by bvwgti** [harman-f/MHI2_MIB2_AIO_FW_Update_Template#6]
Hi,

I am looking into converting either a VW or Audi MIB2 High unit (depending on which can be easily sourced) from G11 to VW NAR G13 firmware. I noticed that it seems that the only AIO for NAR is for Porsche. 

What would be the best way to do this conversion? I assume it is not a trivial endeavor to create a  NAR VW G13 AIO (perhaps an enhancement request?). Would I need to flash the ER G11 firmware, use the ER G13 AIO to do the conversion, and then flash the NAR G13 firmware?

Thanks for any insights and for all of the work you have done!

**Comment by harman-f** [comment]
Here I see ;)

There is no ready to go tool from EU to NAR.
M.I.B has a function implemented to to all regions to EU.

You could look at these scripts and convert them to your needs.

**Comment by bvwgti** [comment]
Hi! Would the best option still be to manually convert the scripts or is converting to EU firmware the best option?

**Comment by harman-f** [comment]
Right, no G13 NAR FW.

You need G13 FW for the bigger screen. Running EU FW in US, might be problematic. I would not recommend it.

**Comment by bvwgti** [comment]
Thanks. What would be problematic about EU FW in US?

**Comment by harman-f** [comment]
Not sure if US maps will work on EU FW.

**Comment by bvwgti** [comment]
I see. Theoretically, I could follow these steps from the wiki to try that though, right? [https://github.com/harman-f/MHI2_MIB2_AIO_FW_Update_Template/wiki/AIO-installation#navigation-region](url)

**Comment by bvwgti** [comment]
It appears that the answer to my above question is yes so long as you know what you are doing.

I think we have gone through the options here so I am going to close this ticket. Thanks again for the all of the help!
