### ISSUE TITLE
Passat GTE dec-2016 conversion

### ISSUE THREAD

**Issue by Ivar247** [harman-f/MHI2_MIB2_AIO_FW_Update_Template#9]
Hi like many I'm looking into your very tempting project to convert my MIB 2.0 in my Passat to MIB 2.5 and 9.1" screen (5G6919606) with new interface.

However I would like to ask some your precious time in order to get some clarity as I also have a virtual cockpit + Dynaudio, which could make the challenge a bit more challenging.

-Virtual cockpit -> I already noticed the version is out of sync updating GW11. Any possibility to update Virtual cockpit when going for GW13 to make sure everything works nicely together?
-Gateway -> Is it needed to update the Gateway to 5WA907530C when updating to GW13 ?
-Dynaudio-AMP -> This seems to be one of the most expensive upgrades required. The firmware mentions I've "VW_MIB2_AMP (45)" does this tell I need to update to an 5Q0035456A AMP ? 

All and all it seems if I need to replace 3 components + flash my virtual cockpit I becomes quite an extensive job where I also expect you need also  some ob2 updates to make sure all new modules are registered properly ?

Cheers again for the feedback !

**Comment by harman-f** [comment]
Well, a bit out of the scope of "just" updating the MIB unit from G11 to G13 ;)

Check with MIB2 TG channel for details.
I think you are right, this will be some work ;)

The upgrade will not touch coding, adaptions or CP, so no issue from that end.
